services:
  wa-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - ./apps/api:/app/apps/api
      - api_node_modules:/app/apps/api/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env.development.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  wa-bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    volumes:
      - ./apps/bot:/app
      - bot_node_modules:/app/node_modules
    env_file:
      - .env.development.local
    restart: unless-stopped

  wa-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.development.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  api_node_modules:
  bot_node_modules:
  web_node_modules:
